In [14]:
import pandas as pd, sqlalchemy as sqla, pymysql as mysql
print(pd.__version__, sqla.__version__)

2.3.3 2.0.39

In [15]:
import os #os is operating system
print(os.getcwd()) #cwd is current working directory
print(os.listdir(r"C:\Users\Saanvi Gupta\Downloads\olist-project")) #checks file directory

c:\Users\Saanvi Gupta\Downloads
['raw', 'README.md']

In [16]:
orders=pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

orders file:
99441 entries
8 columns
all are object datatype
order id and costumer id are unique
order status:
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
no null or duplicate values

In [17]:
print(orders.isnull().sum()) #isnull returns true if its null. true=1 and false=0 and .sum counts the true values in each column
#orders = orders.fillna(0) #replace null with 0
print(orders.duplicated().sum())
print(orders["order_id"].duplicated().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
0
0

In [18]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [19]:
orders["order_status"].value_counts() #.value_counts() — counts the occurrences of each unique value, sorting the counts from highest to lowest by default.

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [20]:
print(orders.nunique())

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

In [21]:
order_items=pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_order_items_dataset.csv")

In [22]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [23]:
order_items.head()
order_items.tail()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [24]:
print(order_items.duplicated().sum())
print(order_items.isnull().sum())
order_items.nunique()

0
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

order_items has
7 columns
112650 entries
here order id isnt unique
whats order_item_id why is it all 1
are there just 21 items
column names are confusing
each order is given a unique id and each costumer is too

In [25]:
reviews=pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_order_reviews_dataset.csv")
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [26]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18-01-2018 00:00,18-01-2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10-03-2018 00:00,11-03-2018 03:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17-02-2018 00:00,18-02-2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21-04-2017 00:00,21-04-2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01-03-2018 00:00,02-03-2018 10:26

In [27]:
reviews['review_id'].nunique()
reviews['order_id'].nunique()

98673

reviews has 7 columns, only review score is int64,should it allow float, review id, order id, score, comment title and messsage

In [28]:
products = pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_products_dataset.csv")
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [29]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [30]:
products.nunique()

product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

In [31]:
print(products.duplicated().value_counts())
print(products.isnull().value_counts())

False    32951
Name: count, dtype: int64
product_id  product_category_name  product_name_lenght  product_description_lenght  product_photos_qty  product_weight_g  product_length_cm  product_height_cm  product_width_cm
False       False                  False                False                       False               False             False              False              False               32340
            True                   True                 True                        True                False             False              False              False                 609
            False                  False                False                       False               True              True               True               True                    1
            True                   True                 True                        True                True              True               True               True                    1
Name: count, dtype: int64

In [32]:
print(products.isnull().sum())

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

products has 32951 entries, product id is unique, why do we have product name length and product description length. 9 columns.
number of null values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2

In [33]:
costumers = pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_customers_dataset.csv")
costumers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [34]:
costumers.nunique()

customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

In [35]:
print(costumers.duplicated().sum())
print(costumers.isnull().sum())

0
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

costumers just has zipcodes and orderIDs

In [36]:
payments = pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_order_payments_dataset.csv")
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [37]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [38]:
print(payments.duplicated().sum())
print(payments.isnull().sum())

0
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [39]:
payments.nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

how is order id not unique for every file
payments has 5 columns showing installments, payment type, amnt etc.

In [40]:
missing = orders[orders["order_delivered_customer_date"].isna()] 
missing["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [41]:
missing1 = orders[orders["order_approved_at"].isna()]
missing1["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [42]:
missing2 = orders[orders["order_delivered_carrier_date"].isna()]
missing2["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

some orders were delivered but had no delivery dats. was left null and can be ignored as it is small

In [43]:
date_cols = [
     "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

"order_purchase_timestamp",
"order_approved_at",
"order_delivered_carrier_date",
"order_delivered_customer_date",
"order_estimated_delivery_date" 
were coverted into date-time

In [44]:
orders[date_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_purchase_timestamp       99441 non-null  datetime64[ns]
 1   order_approved_at              99281 non-null  datetime64[ns]
 2   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 3   order_delivered_customer_date  96476 non-null  datetime64[ns]
 4   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5)
memory usage: 3.8 MB

In [45]:
mask = orders["order_delivered_customer_date"] < orders["order_purchase_timestamp"]
orders.loc[mask].value_counts()
#done to check data sanity

Series([], Name: count, dtype: int64)

In [46]:
orders.groupby(orders["order_purchase_timestamp"].dt.to_period("M")).size()

order_purchase_timestamp
2016-09       4
2016-10     324
2016-12       1
2017-01     800
2017-02    1780
2017-03    2682
2017-04    2404
2017-05    3700
2017-06    3245
2017-07    4026
2017-08    4331
2017-09    4285
2017-10    4631
2017-11    7544
2017-12    5673
2018-01    7269
2018-02    6728
2018-03    7211
2018-04    6939
2018-05    6873
2018-06    6167
2018-07    6292
2018-08    6512
2018-09      16
2018-10       4
Freq: M, dtype: int64

In [47]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])
order_items["shipping_limit_date"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 112650 entries, 0 to 112649
Series name: shipping_limit_date
Non-Null Count   Dtype
--------------   -----
112650 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 880.2 KB

In [48]:
order_items.duplicated(subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [49]:
order_items[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [50]:
sellers=pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\olist_sellers_dataset.csv")

In [51]:
order_items["product_id"].isin(products["product_id"]).all() 
order_items["seller_id"].isin(sellers["seller_id"]).all()
order_items["order_id"].isin(orders["order_id"]).all()
#all gives true only if all values are true and this checks whether all products and sellers listend match the original database

np.True_

In [52]:
orders["customer_id"].isin(costumers["customer_id"]).all()
payments["order_id"].isin(orders["order_id"]).all()
reviews["order_id"].isin(orders["order_id"]).all()

np.True_

In [53]:
(~orders["order_id"].isin(reviews["order_id"])).sum()

np.int64(768)

768 orders have no reviews

In [54]:
reviews.duplicated().sum()

np.int64(0)

In [55]:
reviews["order_id"].duplicated().sum()

np.int64(551)

In [56]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [57]:
reviews["review_id"].duplicated().sum()

np.int64(814)

In [58]:
reviews["review_creation_date"] = pd.to_datetime(reviews["review_creation_date"])
reviews["review_answer_timestamp"] = pd.to_datetime(reviews["review_answer_timestamp"])

C:\Users\Saanvi Gupta\AppData\Local\Temp\ipykernel_23964\3881264926.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  reviews["review_creation_date"] = pd.to_datetime(reviews["review_creation_date"])
C:\Users\Saanvi Gupta\AppData\Local\Temp\ipykernel_23964\3881264926.py:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  reviews["review_answer_timestamp"] = pd.to_datetime(reviews["review_answer_timestamp"])

In [59]:
reviews["review_creation_date"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 99224 entries, 0 to 99223
Series name: review_creation_date
Non-Null Count  Dtype
--------------  -----
99224 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 775.3 KB

In [60]:
products.rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length"                   
 }, inplace=True)

In [61]:
costumers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [62]:
payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [63]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [64]:
costumers["customer_zip_code_prefix"].astype(str).str.zfill(5)

0        14409
1        09790
2        01151
3        08775
4        13056
         ...
99436    03937
99437    06764
99438    60115
99439    92120
99440    06703
Name: customer_zip_code_prefix, Length: 99441, dtype: object

In [65]:
translation = pd.read_csv(r"C:\Users\Saanvi Gupta\Downloads\olist-project\raw\product_category_name_translation.csv")

In [66]:
translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [67]:
products = products.merge(
    translation,
    on="product_category_name",
    how="left"
)

In [68]:
products["product_category_name"] = products["product_category_name"].fillna("unknown")

In [69]:
products["product_category_name_english"] = (
    products["product_category_name_english"]
    .fillna(products["product_category_name"])
)

In [70]:
print(products[[
    "product_category_name",
    "product_category_name_english"
]].head())

print(products["product_category_name_english"].isna().sum())

   product_category_name product_category_name_english
0             perfumaria                     perfumery
1                  artes                           art
2          esporte_lazer                sports_leisure
3                  bebes                          baby
4  utilidades_domesticas                    housewares
0

In [71]:
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:2828sms**@localhost:3306/olist")

In [72]:
with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).scalar())

1

In [73]:
tables = {
    "orders": orders,
    "customers": costumers,
    "products": products,
    "sellers": sellers,
    "reviews": reviews,
    "translation": translation,
    "order_items": order_items,
    "payments": payments
}

for table_name, df in tables.items():
    df.to_sql(
        table_name,
        engine,
        if_exists="replace",
        index=False,
        chunksize=2000
    )

In [74]:
from sqlalchemy.types import String
dtype = {"order_id": String(50), "customer_id": String(50)}

In [1]:
sellers.head()

NameError: name 'sellers' is not defined